### ISSUE TITLE
Release 14.0.0

### ISSUE THREAD

**Issue by Harmon758** [fonttools/unicodedata2#44]
I'm going to be working on the next release, 14.0.0. This is what I anticipate being done:
- [X] Correct 13.0.0-2 tag
  - The 13.0.0-2 tag pointed to https://github.com/fonttools/unicodedata2/commit/c71c98e8853e30b4bc7370ff37bd36165d7971a3, a commit that's part of #38 and not on the master branch of this repository
  - It now points to https://github.com/fonttools/unicodedata2/commit/8b91235e75ebfa5aa4900e966519ef9076983a93, the equivalent commit that merged #38 into the master branch of this repository
  - I've force-pushed the tag to point to the correct commit
- [X] Add changelog for 13.0.0-2 (#45)
  - This was missing in CHANGELOG.md
- [X] Update references to repository (#46)
  - mikekap -> fonttools (#43)
- [X] Drop support for Python 3.5 (#47)
  - [Python 3.5 has been EOL since September 2020](https://www.python.org/dev/peps/pep-0478/)
  - [PyPI Stats shows the download proportion for Python 3.5 to be virtually 0%](https://pypistats.org/packages/unicodedata2)
- [X] Drop support for Python 2(.7) (#48)
  - [Python 2(.7) has been EOL since January 2020](https://www.python.org/dev/peps/pep-0373/)
  - [PyPI Stats shows the download proportion for Python 2.7 to be consistently under 4% and mainly under 1-2%](https://pypistats.org/packages/unicodedata2)
  - I think it's safe to do this now, with it having been EOL for almost two years and the download proportion being so low
  - It would significantly reduce the maintenance burden and make updating for each Unicode version simpler
  - There's precedent for doing this, with support for EOL Python 3.x versions (and 2.6) being dropped in past releases
  - I think continuing to only support versions of Python that are still maintained and not EOL yet ([3.6+ right now](https://devguide.python.org/#branchstatus)) for each release is the best way forward
- [x] Switch from Travis CI to GitHub Actions (#40)
  - [x] Switch from multibuild to cibuildwheel
    - I'm not particularly set on this, but cibuildwheel seems to be easier to set up with GitHub Actions and possibly more readily and regularly maintained/updated, [now that it's a PyPA member project](https://discuss.python.org/t/cibuildwheel-and-the-pypa/8592)
    - It might also be easier to add support for PyPy (#17) with cibuildwheel
- [x] Add support for Python 3.9
  - [Python 3.9 was released October 2020](https://www.python.org/dev/peps/pep-0596/)
  - unicodedata2 13.0.0.post2 (13.0.0-2) has been working with Python 3.9 for me, but support for it still needs to be declared and it would be best to build actual wheels for it
- [x] Add support for Python 3.10
  - [Python 3.10 was released October 2021](https://www.python.org/dev/peps/pep-0619/)
  - unicodedata2 13.0.0.post2 currently fails to install with Python 3.10 for me
- [x] Update to Unicode 14.0
  - [x] Review other relevant commits to CPython since the last unicodedata2 release and consider cherry-picking each one
  - http://blog.unicode.org/2021/09/announcing-unicode-standard-version-140.html
  - https://home.unicode.org/announcing-the-unicode-standard-version-14-0/
  - https://www.unicode.org/versions/Unicode14.0.0/
  - https://bugs.python.org/issue45190
  - https://github.com/python/cpython/pull/28336 (https://github.com/python/cpython/commit/024fda47d40b8cee77ac1cd3d31ee549edc11986)

Feedback is welcome.

**Comment by anthrotype** [comment]
thanks a lot @Harmon758 for taking this on! It all sounds good to me

> continuing to only support versions of Python that are still maintained and not EOL yet (3.6+ right now) for each release is the best way forward

I 100% agree, I think we can drop 2.7 and 3.5, if also @mikekap has no objections.

> cibuildwheel seems to be easier to set up with GitHub Actions and possibly more readily and regularly maintained/updated

👍

**Comment by anthrotype** [comment]
> Switch from Travis CI to GitHub Actions

@Harmon758 I recently did this for py-zopfli, you may want to take a look at
https://github.com/fonttools/py-zopfli/pull/12 and https://github.com/fonttools/py-zopfli/commit/a3473c71e5778576a7553a41209dd9749211aa2b

**Comment by catap** [comment]
I'd love to link my PR: https://github.com/fonttools/unicodedata2/pull/49 whcih allow to build and install `unicodedata2` under Python 3.10

**Comment by anthrotype** [comment]
thanks @catap! I merged the PR and marked the py310 support in the todo list checkboxes

**Comment by catap** [comment]
@anthrotype FYI: I'm adding support of py310 in macports here: https://github.com/macports/macports-ports/pull/13005

You may find backported version for my PR for last release.

I don't think that you need to merge it, but link here seems a good place, because it allow to grab ready to use patch for someone who needed it.

**Comment by anthrotype** [comment]
@Harmon758 let me know if you think there's anything left before we can make the 14.0.0 release, thanks!

**Comment by khaledhosny** [comment]
Can we have the release and fix any issues when they arise?

**Comment by anthrotype** [comment]
https://github.com/fonttools/unicodedata2/releases/tag/14.0.0 - thanks all!
